### ISSUE TITLE
邀請鏈接問題

### ISSUE THREAD

**Issue by microseyuiyuu** [microseyuiyuu/Anime-Club-bot#1]
希望 bot 能夠創建一個新的邀請鏈接並且是基於邀請人的邀請鏈接

**Comment by ray840439** [comment]
** 邀請進入 json檔案顯示 **
json檔案出現以下
{
    "invites": {
        "1214974213597822986": 3,
        "1043354673874206751": 5,
        "973146538257833984": 7
    },
    "channel_id": 1263733274472087610,
    "invite_creators": {
        "NwYYNkJ": 973146538257833984,
        "N6AaSHa72E": 973146538257833984
    }
}

從內容來看BOT獲取了以前用戶的邀請紀錄 我不希望機器人獲取 用戶之前的邀請紀錄

**Comment by microseyuiyuu** [comment]
> **邀請進入 json檔案顯示** json檔案出現以下 { "invites": { "1214974213597822986": 3, "1043354673874206751": 5, "973146538257833984": 7 }, "channel_id": 1263733274472087610, "invite_creators": { "NwYYNkJ": 973146538257833984, "N6AaSHa72E": 973146538257833984 } }
> 
> 從內容來看BOT獲取了以前用戶的邀請紀錄 我不希望機器人獲取 用戶之前的邀請紀錄

请查看现在版本：https://github.com/microseyuiyuu/Anime-Club-bot/blob/main/an.py

**Comment by ray840439** [comment]
##解決##
